import { Camera, BookOpen, ChefHat, Search } from "lucide-react";

export const SITE_STATS = [
  { label: "Free Scans", val: "10/mo" },
  { label: "Recipes Generated", val: "1M+" },
  { label: "Cost to Start", val: "$0" },
  { label: "App Store Rating", val: "4.9" },
];

export const FEATURES = [
  {
    title: "Scan Your Pantry",
    description:
      "Photo recognition that actually works. Know what you have instantly.",
    icon: Camera,
    limit: "10 scans/mo free",
  },
  {
    title: "AI Chef Suggestions",
    description:
      "Turn random ingredients into a gourmet meal. Zero food waste.",
    icon: ChefHat,
    limit: "5 meals/mo free",
  },
  {
    title: "Search Any Dish",
    description:
      "Find any recipe instantly. Filter by cuisine, time, or dietary needs.",
    icon: Search,
    limit: "Unlimited searches",
  },
  {
    title: "Digital Cookbook",
    description: "Save your favorites. Export as PDF. Share with family.",
    icon: BookOpen,
    limit: "3 saves/mo free",
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Scan",
    desc: "Point camera at fridge. AI identifies ingredients.",
  },
  {
    step: "02",
    title: "Select",
    desc: "Choose a generated recipe based on your mood.",
  },
  {
    step: "03",
    title: "Savor",
    desc: "Follow simple steps. Eat delicious food.",
  },
];

// Helper function for category emojis
export function getCategoryEmoji(category) {
  const emojiMap = {
    Beef: "🥩",
    Chicken: "🍗",
    Dessert: "🍰",
    Lamb: "🍖",
    Miscellaneous: "🍴",
    Pasta: "🍝",
    Pork: "🥓",
    Seafood: "🦐",
    Side: "🥗",
    Starter: "🥟",
    Vegan: "🥬",
    Vegetarian: "🥕",
    Breakfast: "🍳",
    Goat: "🐐",
  };
  return emojiMap[category] || "🍽️";
}

// Helper function for country flags
export function getCountryFlag(country) {
  const emojiMap = {
    American: "🗽",
    British: "👑",
    Canadian: "🍁",
    Chinese: "🐉",
    Croatian: "⚽",
    Dutch: "🌷",
    Egyptian: "🐫",
    Filipino: "🌴",
    French: "🥐",
    Greek: "🏛️",
    Indian: "🪷",
    Irish: "☘️",
    Italian: "🍕",
    Jamaican: "🌴",
    Japanese: "🗾",
    Kenyan: "🦒",
    Malaysian: "🌺",
    Mexican: "🌮",
    Moroccan: "🕌",
    Polish: "🦅",
    Portuguese: "🚢",
    Russian: "❄️",
    Spanish: "💃",
    Thai: "🛕",
    Tunisian: "🏜️",
    Turkish: "🧿",
    Ukrainian: "🌻",
    Vietnamese: "🍜",
    Algerian: "🏜️",
    Argentinian: "⚽",
    Australian: "🦘",
    Norwegian: "❄️",
    "Saudi Arabian": "🕋",
    Slovakian: "🏔️",
    Syrian: "🏛️",
    Uruguayan: "⚽",
    Venezuelan: "🌞",
    Dominican: "🏖️",
    Afghan: "⛰️",
    Brazilian: "🦜",
    Cambodian: "🛕",
    Cuban: "💃",
    German: "🥨",
    Indonesian: "🌋",
    Argentine: "⚽",  
    Slovak: "🏔️",   
    Turkish: "🥙",
    Israeli: "🧆",
    Lebanese: "🥙",
    Albanian: "🦅",
    Andorran: "🏔️",
    Angolan: "☀️",
    "Antiguan, Barbudan": "🐚",
    Armenian: "🍇",
    Aruban: "🏖️",
    Austrian: "🏔️",
    Azerbaijani: "🔥",
    Bahamian: "🦩",
    Bahraini: "🕌",
    Bangladeshi: "🐅",
    Barbadian: "🔱",
    Belarusian: "🌲",
    Belgian: "🧇",
    Belizean: "🌴",
    Beninese: "🐆",
    Bermudian: "🩳",
    Bhutanese: "🐉",
    Bolivian: "🦙",
    "Bosnian, Herzegovinian": "☕",
    Motswana: "🦓",
    Bruneian: "🕌",
    Bulgarian: "🌹",
    Burkinabe: "🦁",
    Burundian: "🥁",
    Cameroonian: "🦁",
    "Cape Verdian": "🌊",
    Caymanian: "🐢",
    "Central African": "🐘",
    Chadian: "🏜️",
    Chilean: "🌶️",
    Colombian: "☕",
    "Costa Rican": "🦜",
    Cypriot: "🫒",
    Czech: "🍺",
    Danish: "🏰",
    Djibouti: "🏜️",
    Congolese: "🦍",
    Ecuadorean: "🐢",
    Salvadoran: "🌊",
    "Equatorial Guinean": "🌴",
    Eritrean: "🐪",
    Estonian: "🌲",
    Ethiopian: "☕",
    Faroese: "🐑",
    Fijian: "🏖️",
    Finnish: "🌲",
    Gabonese: "🦍",
    Gambian: "🦜",
    Georgian: "🍷",
    Ghanaian: "🍫",
    Gibraltar: "🪨",
    Greenlandic: "🧊",
    Grenadian: "🌶️",
    Guadeloupian: "🌊",
    Guamanian: "🌴",
    Guatemalan: "🦜",
    "Channel Islander": "🐮",
    Guinean: "🍉",
    "Guinea-Bissauan": "🌴",
    Guyanese: "🦜",
    Haitian: "🥭",
    Honduran: "🦜",
    "Hong Konger": "🥮",
    Hungarian: "🥣",
    Icelander: "🌋",
    Ivorian: "🍫",
    Jordanian: "🏛️",
    Kazakhstani: "🦅",
    Kosovar: "🏔️",
    Kuwaiti: "🦅",
    Kirghiz: "🐎",
    Laotian: "🐘",
    Latvian: "🌲",
    Mosotho: "🏔️",
    Liberian: "🌴",
    Libyan: "🏜️",
    Liechtensteiner: "🏰",
    Lithuanian: "🌲",
    Luxembourger: "🏰",
    Malagasy: "🦎",
    Malawian: "🐆",
    Maldivan: "🏝️",
    Malian: "🏜️",
    Maltese: "🏛️",
    Mauritian: "🦤",
    Moldovan: "🍇",
    Mongolian: "🐎",
    Montenegrin: "🦅",
    Mozambican: "🦁",
    Burmese: "🛕",
    Namibian: "🏜️",
    Nepalese: "🏔️",
    "New Zealander": "🥝",
    Nicaraguan: "🌋",
    Nigerien: "🏜️",
    Nigerian: "🦅",
    "North Korean": "🍚",
    Macedonian: "🏛️",
    Omani: "🕌",
    Pakistani: "🕌",
    Palestinian: "🫒",
    Panamanian: "🦜",
    "Papua New Guinean": "🦜",
    Paraguayan: "🦅",
    Peruvian: "🦙",
    "Puerto Rican": "🏝️",
    Qatari: "🦅",
    Romanian: "🏰",
    Rwandan: "🦍",
    "Saint Lucian": "🦜",
    Samoan: "🥥",
    Sammarinese: "🏰",
    Senegalese: "🦁",
    Serbian: "🦅",
    Seychellois: "🐢",
    "Sierra Leonean": "💎",
    Singaporean: "🦁",
    Slovene: "🏔️",
    "Solomon Islander": "🏝️",
    Somali: "🐪",
    "South African": "🦁",
    "South Korean": "🥢",
    "South Sudanese": "🐆",
    "Sri Lankan": "🇱🇰",
    Sudanese: "🐪",
    Surinamer: "🌴",
    Swedish: "🦌",
    Swiss: "🧀",
    Taiwanese: "🧋",
    Tadzhik: "🏔️",
    Tanzanian: "🦁",
    Togolese: "🦁",
    Tongan: "🥥",
    Trinidadian: "🏝️",
    Turkmen: "🐎",
    Tuvaluan: "🏝️",
    Ugandan: "🦍",
    Emirati: "🦅",
    Uzbekistani: "🕌",
    "Ni-Vanuatu": "🏝️",
    Yemeni: "🏰",
    Zambian: "🦅",
    Zimbabwean: "🇿🇼"
  };

  return emojiMap[country] ?? "🌍";
}